### ISSUE TITLE
When training the PSGTR with 3090, RuntimeError encountered!

### ISSUE THREAD

**Issue by hszhoushen** [Jingkang50/OpenPSG#44]
When using cuda11.1, torch1.8.0, mmcv1.4.3, 3090

python -m pdb -c continue tools/train.py \
       configs/psgtr/psgtr_r101_psg.py

```
wandb: 🚀 View run at https://wandb.ai/hszhoushen/psgtr/runs/3nmjnxmg
/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/site-packages/mmdet/models/losses/cross_entropy_loss.py:239: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  self.class_weight, device=cls_score.device)
Traceback (most recent call last):
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/data/lgzhou/psgg/OpenPSG/tools/train.py", line 2, in <module>
    import argparse
  File "/data/lgzhou/psgg/OpenPSG/tools/train.py", line 223, in main
    meta=meta,
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/site-packages/mmdet/apis/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA error: an illegal memory access was encountered
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/lgzhou/.conda/envs/sg_benchmark/lib/python3.7/site-packages/torch/autograd/__init__.py(147)backward()
-> allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
(Pdb) exit()
Post mortem debugger finished. The tools/train.py will be restarted
> /data/lgzhou/psgg/OpenPSG/tools/train.py(2)<module>()
-> import argparse
(Pdb) exit

```

**Comment by Jingkang50** [comment]
Seems like your cuda drive does not match your cudatoolkit version.

**Comment by llipa** [comment]
Hello, have you solve this problem. I meet the same error when training PSGTR with 3090. Could you help me solving this problem.
