### ISSUE TITLE
Questions about training psgformer on multiple GPUs ?

### ISSUE THREAD

**Issue by FXLYZ** [Jingkang50/OpenPSG#53]
Hi,
when i train psgformer on multiple GPUs (2x3090), i get the error with NCCL. :)

### RuntimeError: Connection reset by peer

(openpsg) zztao@zztao-Precision-5820-Tower:~/dev/OpenPSG$ PYTHONPATH='.':$PYTHONPATH python -m torch.distributed.launch --nproc_per_node=2 --master_port=29500   tools/train.py   configs/psgformer/psgformer_r50_psg.py   --gpus 2   --launcher pytorch
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
zztao-Precision-5820-Tower:35819:35819 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
zztao-Precision-5820-Tower:35819:35819 [0] NCCL INFO NCCL_SOCKET_IFNAME set to eth0

zztao-Precision-5820-Tower:35819:35819 [0] bootstrap.cc:32 NCCL WARN Bootstrap : no socket interface found
zztao-Precision-5820-Tower:35819:35819 [0] NCCL INFO init.cc:101 -> 3
zztao-Precision-5820-Tower:35819:35819 [0] NCCL INFO init.cc:123 -> 3
zztao-Precision-5820-Tower:35819:35819 [0] NCCL INFO init.cc:140 -> 3
Traceback (most recent call last):
  File "tools/train.py", line 225, in <module>
    main()
  File "tools/train.py", line 124, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 32, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729047590/work/torch/lib/c10d/ProcessGroupNCCL.cpp:748, internal error, NCCL version 2.7.8
Traceback (most recent call last):
  File "tools/train.py", line 225, in <module>
    main()
  File "tools/train.py", line 124, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 32, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: Connection reset by peer
Traceback (most recent call last):
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/zztao/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zztao/anaconda3/envs/openpsg/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/psgformer/psgformer_r50_psg.py', '--gpus', '2', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by Hanzy1996** [comment]
I have the same question. Could you please share how you solve it?

Best Regards.
