### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by llipa** [Jingkang50/OpenPSG#70]
I got an error when training PSGTR: python tools/train.py configs/psgtr/psgtr_r50_psg.py --gpus 1

Traceback (most recent call last):
  File "tools/train.py", line 225, in <module>
    main()
  File "tools/train.py", line 220, in main
    meta=meta,
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/mmdet/apis/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/llipa/anaconda3/envs/openpsg/lib/python3.7/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

It seems that the dataset config file goes wrong: https://github.com/open-mmlab/mmdetection/issues/3628

**Comment by llipa** [comment]
Sorry that i mistook the 'ann_file' setting in configs/_base_/datasets/psg.py.

**Comment by anshudaur** [comment]
> Sorry that i mistook the 'ann_file' setting in configs/_base_/datasets/psg.py.
Hey @llipa ,
can you explain "mistook" for what?

i have annotation files converted to coco format .. and i am also getting this error for registered custom dataset in coco format.

Thank you
Anshu
