### ISSUE TITLE
Validation:AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by wyz-gitt** [Jingkang50/OpenPSG#9]
Hello, first of all I am very interested in your work. I try to run your code, when I run an epoch and save the model for validation, I get an error:

2022-08-01 23:10:31,978 - mmdet - INFO - Epoch [1][5650/5713]   lr: 3.000e-02, eta: 17:35:21, time: 0.996, data_time: 0.162, memory: 3983, loss_object: 0.9221, acc_object: 71.2541, loss_relation: 0.1331, acc_relation: 96.9015, loss: 1.0552, grad_norm: 2.0675
2022-08-01 23:11:22,457 - mmdet - INFO - Epoch [1][5700/5713]   lr: 3.000e-02, eta: 17:34:32, time: 1.010, data_time: 0.169, memory: 3983, loss_object: 0.9318, acc_object: 70.6544, loss_relation: 0.1167, acc_relation: 97.2933, loss: 1.0485, grad_norm: 2.0553
2022-08-01 23:11:35,678 - mmdet - INFO - Saving checkpoint at 1 epochs
[                                                  ] 0/2177, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 231, in <module>
    main()
  File "tools/train.py", line 226, in main
    meta=meta,
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmdet/apis/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 56, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmdet/apis/test.py", line 26, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/openpsg/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 214, in __getitem__
    return self.prepare_test_img(idx)
  File "/home/wangyize/OpenPSG/openpsg/datasets/psg.py", line 289, in prepare_test_img
    return self.prepare_train_img(idx)
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 239, in prepare_train_img
    return self.pipeline(results)
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/wangyize/.local/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 73, in __call__
    results['img_shape'] = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

The path of the training data set in the configuration file is the same as the path of the verification data set. There is no problem in the training process. The error reported during verification should be that no pictures were found. Did you encounter this problem? Looking forward to your reply!

**Comment by Jingkang50** [comment]
Thank you for your interest in our work!
Could you show us the script you are running?

**Comment by wyz-gitt** [comment]
> Thank you for your interest in our work! Could you show us the script you are running?

I run the tools/train.py and the config is configs/motifs/panoptic_fpn_r101_fpn_1x_sgdet_psg.py .In the code you provided the path should be scripts\motifs\train_panoptic_fpn_r101_sgdet.sh

**Comment by Jingkang50** [comment]
We did not meet the similar bug before. 
As you said, this should due to the wrong coco path.
Maybe use pdb to check which image is missing?

**Comment by wyz-gitt** [comment]
> We did not meet the similar bug before. As you said, this should due to the wrong coco path. Maybe use pdb to check which image is missing?

Thanks for your reply, I will try it！I hope i can solve it.

**Comment by wyz-gitt** [comment]
> We did not meet the similar bug before. As you said, this should due to the wrong coco path. Maybe use pdb to check which image is missing?

Can you provide the complete training and testing log file, thank you！I have been unable to solve this bug, and there is another problem. The val in the dataset you provided is the validation set, right? But in dada/coco I can't find the file of your test set, how is your data set divided into test set?

**Comment by Jingkang50** [comment]
I just upload an example [log](https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/Eqe8gFwdEN1Aj1dSrcr196IBs95YuD-H_HP8YUKDmwUftQ?e=24GUXD) from VCTree R50 predcls. 

The split of train/test is stored in `psg.json`. Maybe you could play with the data from https://github.com/Jingkang50/OpenPSG/blob/main/tools/Visualize_Dataset.ipynb.

**Comment by wyz-gitt** [comment]
> I just upload an example [log](https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/Eqe8gFwdEN1Aj1dSrcr196IBs95YuD-H_HP8YUKDmwUftQ?e=24GUXD) from VCTree R50 predcls.
> 
> The split of train/test is stored in the psg json files. Maybe you could play with the data from https://github.com/Jingkang50/OpenPSG/blob/main/tools/Visualize_Dataset.ipynb.

Thanks again for your reply! The problem has been solved, because of network problems, there was an error when decompressing the val2017 dataset!

**Comment by Jingkang50** [comment]
Ah! Glad to hear that you solve the problem! Thank you and good luck on your PSG journey!
